### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by Marcuse7**
Fix broken repo link

### Test plan

1. Click on corrected link to check if repo available

### CODE REVIEW

**Comment by Strum355** [comment]
@olafurpg I'd imagine we want to direct kotlin issues to https://github.com/sourcegraph/lsif-kotlin instead of this repo. Either way the existing link is wrong though. That being said, should we rename the lsif-kotlin repo to semanticdb-kotlin? Would be good to update the [project name here](https://github.com/sourcegraph/lsif-kotlin/blob/main/settings.gradle.kts#L2) too then, the maven coordinates should be unaffected as theyre `com.sourcegraph:semanticdb-kotlinc` anyways.

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻 I'm OK with directing issues at scip-java instead of the Kotlin repo. I'm +1 with renaming the lsif-kotlin repo into semanticdb-kotlin

**Comment by olafurpg** [comment]
@Marcuse7 Thank you for this contribution!

**Comment by Strum355** [comment]
Think the PR just needs to be rebased so that CI passes, and then we should be good to go @Marcuse7

**Comment by Marcuse7** [comment]
Sorry, was about to mess up the history.

**Pull request closed without merging**
